// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// Generate is an autogenerated mock type for the Generate type
type Generate struct {
	mock.Mock
}

// Time provides a mock function with no fields
func (_m *Generate) Time() time.Time {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Time")
	}

	var r0 time.Time
	if rf, ok := ret.Get(0).(func() time.Time); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}

// UUID provides a mock function with no fields
func (_m *Generate) UUID() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for UUID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewGenerate creates a new instance of Generate. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGenerate(t interface {
	mock.TestingT
	Cleanup(func())
}) *Generate {
	mock := &Generate{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
