// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	transaction "amartha-recon-service/infrastructure/repository/transaction"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// FindDistinctBankCode provides a mock function with given fields: ctx
func (_m *Repository) FindDistinctBankCode(ctx context.Context) ([]*transaction.Transaction, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindDistinctBankCode")
	}

	var r0 []*transaction.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*transaction.Transaction, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*transaction.Transaction); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*transaction.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindTransaction provides a mock function with given fields: ctx, tc
func (_m *Repository) FindTransaction(ctx context.Context, tc *transaction.Criteria) ([]*transaction.Transaction, error) {
	ret := _m.Called(ctx, tc)

	if len(ret) == 0 {
		panic("no return value specified for FindTransaction")
	}

	var r0 []*transaction.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *transaction.Criteria) ([]*transaction.Transaction, error)); ok {
		return rf(ctx, tc)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *transaction.Criteria) []*transaction.Transaction); ok {
		r0 = rf(ctx, tc)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*transaction.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *transaction.Criteria) error); ok {
		r1 = rf(ctx, tc)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
