// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	recon "amartha-recon-service/application/recon"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// Proceed provides a mock function with given fields: ctx, file
func (_m *Service) Proceed(ctx context.Context, file *recon.UploadFile) (recon.ShowResultReconciliation, error) {
	ret := _m.Called(ctx, file)

	if len(ret) == 0 {
		panic("no return value specified for Proceed")
	}

	var r0 recon.ShowResultReconciliation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *recon.UploadFile) (recon.ShowResultReconciliation, error)); ok {
		return rf(ctx, file)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *recon.UploadFile) recon.ShowResultReconciliation); ok {
		r0 = rf(ctx, file)
	} else {
		r0 = ret.Get(0).(recon.ShowResultReconciliation)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *recon.UploadFile) error); ok {
		r1 = rf(ctx, file)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
